{
 "title": "local_exporter_v2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "scen", "label": "scenario", "query": "label_values(scen)" }
  ]
 },
 "panels": [
  { "title": "Details for $scen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "scen" },
  {
   "title": "Process Details with State 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"}",
     "legendFormat": "current process duration"
    },
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[${__range_s}s])",
     "legendFormat": "average process duration"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[${__range_s}s])) * 1.25",
     "legendFormat": "processes with overtime"
    }
   ]
  },
  {
   "title": "Process Details with State 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"2\"}",
     "legendFormat": "current process duration"
    },
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"2\"}[${__range_s}s])",
     "legendFormat": "average process duration"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"2\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"2\"}[${__range_s}s])) * 1.25",
     "legendFormat": "processes with overtime"
    }
   ]
  },
  {
   "title": "Process Details with State 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"}",
     "legendFormat": "current process duration"
    },
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[${__range_s}s])",
     "legendFormat": "average process duration"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[${__range_s}s])) * 1.25",
     "legendFormat": "processes with overtime"
    }
   ]
  }
 ]
}