{
 "title": "Oracle DB",
 "description": "oracledb dashboard",
 "tags": [ "oracle" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "SID", "query": "label_values(oracledb_up, SID)" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "oracledb status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(oracledb_sessions_value{SID=\"$SID\", status=\"ACTIVE\"})"
    }
   ]
  },
  {
   "title": "user commits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "execute count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "last scrape duration seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_exporter_last_scrape_duration_seconds{SID=\"$SID\"}"
      }
     ]
    },
    {
     "title": "total scrapes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_exporter_scrapes_total{SID=\"$SID\"}"
      }
     ]
    }
   ]
  },
  { "title": "Load & Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "resource utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (oracledb_resource_current_utilization{SID=\"$SID\"} / oracledb_resource_limit_value{SID=\"$SID\"}) by (resource_name)",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "tablespaces %used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(oracledb_tablespace_bytes{SID=\"$SID\"} - oracledb_tablespace_free{SID=\"$SID\"}) / oracledb_tablespace_bytes{SID=\"$SID\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_sessions_value{SID=\"$SID\", status=\"ACTIVE\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Wait times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "wait time concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "wait time commit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "wait time system io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "wait time user io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "wait time application",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{SID=\"$SID\"}"
    }
   ]
  },
  {
   "title": "wait time network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{SID=\"$SID\"}"
    }
   ]
  }
 ]
}