{
 "title": "local-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "scen", "label": "scen", "query": "label_values(scen)" }
  ]
 },
 "panels": [
  { "title": "state 1 for $scen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "scen" },
  {
   "title": "state 3 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  },
  {
   "title": "count fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))"
    }
   ]
  },
  {
   "title": "count fail clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "clamp_max(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])), 1)"
    }
   ]
  },
  {
   "title": "calc traffic light",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "count ot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))"
    }
   ]
  },
  {
   "title": "count ot clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:])) - 1"
    },
    {
     "expr": "clamp_max(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]), 1)"
    }
   ]
  },
  {
   "title": "state 1 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  },
  { "title": "state 1 for $scen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "state 3 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  },
  {
   "title": "count fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))"
    }
   ]
  },
  {
   "title": "count fail clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "clamp_max(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])), 1)"
    }
   ]
  },
  {
   "title": "calc traffic light",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "count ot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))"
    }
   ]
  },
  {
   "title": "count ot clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:])) - 1"
    },
    {
     "expr": "clamp_max(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]), 1)"
    }
   ]
  },
  {
   "title": "state 1 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  },
  { "title": "state 1 for $scen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "state 3 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"3\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  },
  {
   "title": "count fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))"
    }
   ]
  },
  {
   "title": "count fail clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m]))) - 1"
    },
    {
     "expr": "clamp_max(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"3\"}[15m])), 1)"
    }
   ]
  },
  {
   "title": "calc traffic light",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "count ot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))) - 1"
    },
    {
     "expr": "sum(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]))"
    }
   ]
  },
  {
   "title": "count ot clamped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "absent(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:])) - 1"
    },
    {
     "expr": "clamp_max(count_over_time(local_dur_total{scen=\"$scen\", state=\"1\"} > ((avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25)[15m:]), 1)"
    }
   ]
  },
  {
   "title": "state 1 details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])",
     "legendFormat": "avg dur {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"} > (avg_over_time(local_dur_total{scen=\"$scen\", state=\"1\"}[15m])) * 1.25",
     "legendFormat": "overtime {{pm}}"
    },
    {
     "expr": "local_dur_total{scen=\"$scen\", state=\"1\"}",
     "legendFormat": "cur dur {{pm}}"
    }
   ]
  }
 ]
}